/*
 * TPVV
 *
 * TPVV Ingeniería Web
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lac56@alu.ua.es
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using System.Runtime.Serialization;
using System.Linq;
using MySql.Data.MySqlClient;
using static IO.Swagger.Models.Devoluciones;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DevolucionesApiController : ControllerBase
    {
        private MySqlConnection conn;
        string stringConexion = "server=localhost;port=3306;user id=luis;password=root;database=iw;SslMode=none";
        private bool comprobarToken(string token)
        {
            MySqlCommand cmd2 = new MySqlCommand();
            cmd2.Connection = conn;
            cmd2.CommandText = "SELECT * FROM iw.almacentokens where token = '" + token + "'";
            cmd2.ExecuteNonQuery();
            MySqlDataReader readerKey = cmd2.ExecuteReader();
            bool comprobarKey = false;

            while (readerKey.Read())
            {
                if (token == readerKey.GetString(1))
                {
                    comprobarKey = true;
                    break;
                }
            }

            return comprobarKey;
        }
        private string GetValue(EstadoEnum? paymentStatus)
        {
            EnumMemberAttribute attribute = paymentStatus
                .GetType()
                .GetField(paymentStatus.ToString())
                .GetCustomAttributes(typeof(EnumMemberAttribute), false)
                .SingleOrDefault() as EnumMemberAttribute;

            return attribute?.Value;
        }
        /// <summary>
        /// Obtendremos los detalles de una devolucion en concreto
        /// </summary>
        /// <remarks>Obtendremos los detalles de una devolucion en concreto</remarks>
        /// <param name="token"></param>
        /// <param name="idPago"></param>
        /// <response code="200">Detalles sobre la transaccion</response>
        /// <response code="400">Esta respuesta significa que el servidor no pudo interpretar la solicitud dada una sintaxis inválida.</response>
        /// <response code="401">Sin autorización para realizar esta operación</response>
        /// <response code="404">No se encontró el recurso que se pidió</response>
        [HttpGet]
        [Route("/lac56-alu/TPVV/1.0.0/tpvv/detallesDevolucion")]
        [ValidateModelState]
        [SwaggerOperation("GetDetallesDevolucion")]
        [SwaggerResponse(statusCode: 200, type: typeof(Devoluciones), description: "Detalles sobre la transaccion")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Esta respuesta significa que el servidor no pudo interpretar la solicitud dada una sintaxis inválida.")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse401), description: "Sin autorización para realizar esta operación")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse404), description: "No se encontró el recurso que se pidió")]
        public virtual IActionResult GetDetallesDevolucion([FromQuery][Required()]string token, [FromQuery][Required()]int? idPago)
        {
            conn = new MySqlConnection(stringConexion);
            conn.Open();
            MySqlCommand cmd = new MySqlCommand();
            cmd.Connection = conn;
            InlineResponse200 resp = new InlineResponse200();

            if (comprobarToken(token))
            {
                conn = new MySqlConnection(stringConexion);
                conn.Open();
                MySqlCommand cmd2 = new MySqlCommand();
                cmd2.Connection = conn;
                cmd2.CommandText = "SELECT * FROM iw.devoluciones where fk_pago = " + idPago.ToString() + "";
                cmd2.ExecuteNonQuery();

                Devoluciones devolucionItem = new Devoluciones();
                MySqlDataReader reader = cmd2.ExecuteReader();

                while (reader.Read())
                {
                    devolucionItem = new Devoluciones();
                    devolucionItem.Id = Convert.ToInt32(reader.GetString(0));
                    devolucionItem.Total = Convert.ToDecimal(reader.GetString(1));
                    devolucionItem.Concepto = reader.GetString(2);
                    devolucionItem.Referencia = reader.GetString(3);
                    devolucionItem.Fecha = reader.GetString(4);
                    if (reader.GetString(5).Equals("EN_ESPERA"))
                    {
                        devolucionItem.Estado = Devoluciones.EstadoEnum.ENESPERAEnum;
                    }
                    else
                    {
                        if (reader.GetString(5).Equals("ACEPTADO"))
                        {
                            devolucionItem.Estado = Devoluciones.EstadoEnum.ACEPTADOEnum;
                        }
                        else
                        {
                            devolucionItem.Estado = Devoluciones.EstadoEnum.DENEGADODEVOLUCINEnum;
                        }
                    }
                    devolucionItem.DetallesEstado = reader.GetString(6);

                    conn.Close();
                    return StatusCode(200, devolucionItem);
                }

                InlineResponse404 resp3 = new InlineResponse404();
                resp3.ErrorMessage = "ERROR_RECURSO_NO_ENCONTRADO";
                conn.Close();
                return StatusCode(404, resp3);
            }
            else
            {
                InlineResponse401 resp2 = new InlineResponse401();
                resp2.ErrorMessage = "ERROR_TOKEN";
                conn.Close();
                return StatusCode(401, resp2);
            }

            return StatusCode(200, resp);
        }

        /// <summary>
        /// Se listan todas las devoluciones del usuario
        /// </summary>
        /// <remarks>Se obtienen una lista con todas las devoluciones que se han realizado por el usuario que hace la petición</remarks>
        /// <param name="token"></param>
        /// <response code="200">Lista de las devoluciones</response>
        /// <response code="401">Sin autorización para realizar esta operación</response>
        [HttpGet]
        [Route("/lac56-alu/TPVV/1.0.0/tpvv/listaDevoluciones")]
        [ValidateModelState]
        [SwaggerOperation("GetListaDevoluciones")]
        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse2001), description: "Lista de las devoluciones")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse401), description: "Sin autorización para realizar esta operación")]
        public virtual IActionResult GetListaDevoluciones([FromQuery][Required()]string token)
        {
            conn = new MySqlConnection(stringConexion);
            conn.Open();
            MySqlCommand cmd = new MySqlCommand();
            cmd.Connection = conn;
            InlineResponse200 resp = new InlineResponse200();

            if (comprobarToken(token))
            {
                conn = new MySqlConnection(stringConexion);
                conn.Open();
                MySqlCommand cmd2 = new MySqlCommand();
                cmd2.Connection = conn;
                cmd2.CommandText = "SELECT * FROM iw.devoluciones";
                cmd2.ExecuteNonQuery();

                Devoluciones devolucionItem = new Devoluciones();
                MySqlDataReader reader = cmd2.ExecuteReader();
                List<Devoluciones> listaDevoluciones = new List<Devoluciones>();

                while (reader.Read())
                {
                    devolucionItem = new Devoluciones();
                    devolucionItem.Id = Convert.ToInt32(reader.GetString(0));
                    devolucionItem.Total = Convert.ToDecimal(reader.GetString(1));
                    devolucionItem.Concepto = reader.GetString(2);
                    devolucionItem.Referencia = reader.GetString(3);
                    devolucionItem.Fecha = reader.GetString(4);
                    if (reader.GetString(5).Equals("EN_ESPERA"))
                    {
                        devolucionItem.Estado = Devoluciones.EstadoEnum.ENESPERAEnum;
                    }
                    else
                    {
                        if (reader.GetString(5).Equals("ACEPTADO"))
                        {
                            devolucionItem.Estado = Devoluciones.EstadoEnum.ACEPTADOEnum;
                        }
                        else
                        {
                            devolucionItem.Estado = Devoluciones.EstadoEnum.DENEGADODEVOLUCINEnum;
                        }
                    }
                    devolucionItem.DetallesEstado = reader.GetString(6);
                    listaDevoluciones.Add(devolucionItem);
                }

                if (listaDevoluciones.Count > 0)
                {
                    conn.Close();
                    return StatusCode(200, listaDevoluciones);
                }

                InlineResponse404 resp3 = new InlineResponse404();
                resp3.ErrorMessage = "ERROR_RECURSO_NO_ENCONTRADO";
                conn.Close();
                return StatusCode(404, resp3);
            }
            else
            {
                InlineResponse401 resp2 = new InlineResponse401();
                resp2.ErrorMessage = "ERROR_TOKEN";
                conn.Close();
                return StatusCode(401, resp2);
            }
        }

        /// <summary>
        /// Realizar una devolución sobre una de las compras realizadas
        /// </summary>
        /// <remarks>Realizar una devolución sobre una de las compras realizadas</remarks>
        /// <param name="token"></param>
        /// <param name="idPago"></param>
        /// <response code="201">Detalles sobre la transaccion</response>
        /// <response code="400">Esta respuesta significa que el servidor no pudo interpretar la solicitud dada una sintaxis inválida.</response>
        /// <response code="401">Sin autorización para realizar esta operación</response>
        /// <response code="404">No se encontró el recurso que se pidió</response>
        [HttpPost]
        [Route("/lac56-alu/TPVV/1.0.0/tpvv/realizarDevolucion")]
        [ValidateModelState]
        [SwaggerOperation("RealizarDevolucion")]
        [SwaggerResponse(statusCode: 201, type: typeof(Devoluciones), description: "Detalles sobre la transaccion")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Esta respuesta significa que el servidor no pudo interpretar la solicitud dada una sintaxis inválida.")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse401), description: "Sin autorización para realizar esta operación")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse404), description: "No se encontró el recurso que se pidió")]
        public virtual IActionResult RealizarDevolucion([FromQuery][Required()]string token, [FromQuery][Required()]int? idPago)
        {
            conn = new MySqlConnection(stringConexion);
            conn.Open();
            MySqlCommand cmd = new MySqlCommand();
            cmd.Connection = conn;
            InlineResponse201 resp = new InlineResponse201();

            if (comprobarToken(token))
            {
                conn = new MySqlConnection(stringConexion);
                conn.Open();
                MySqlCommand cmd2 = new MySqlCommand();
                cmd2.Connection = conn;
                cmd2.CommandText = "SELECT * FROM iw.pagos where id = " + idPago.ToString() + "";
                cmd2.ExecuteNonQuery();

                string total = "", concepto = "", referencia = "", fecha = "", estado = "", detalles = "";
                MySqlDataReader reader = cmd2.ExecuteReader();

                if (reader.Read() == false)
                {
                    InlineResponse404 resp3 = new InlineResponse404();
                    resp3.ErrorMessage = "ERROR_RECURSO_NO_ENCONTRADO";
                    conn.Close();
                    return StatusCode(404, resp3);
                }
                else
                {
                    total = reader.GetString(1);
                    concepto = reader.GetString(2);
                    referencia = reader.GetString(3);
                    fecha = reader.GetString(4);
                    estado = reader.GetString(5);
                    detalles = reader.GetString(6);
                    conn.Close();
                }
                try
                {
                    conn = new MySqlConnection(stringConexion);
                    conn.Open();
                    MySqlCommand cmd3 = new MySqlCommand();
                    cmd3.Connection = conn;
                    cmd3.CommandText = "INSERT INTO iw.devoluciones (total, concepto, referencia, fecha, estado, detallesEstado,fk_pago) VALUES ('" +
                        total + "', '" + concepto + "', '" + referencia
                        + "',now()" + ", '" + "DENEGADO, DEVOLUCIÓN" + "','" + detalles + "', '" + idPago + "');";
                    cmd3.ExecuteNonQuery();
                    conn.Close();
                    conn.Open();
                    MySqlCommand cmd4 = new MySqlCommand();
                    cmd4.Connection = conn;
                    cmd4.CommandText = "update iw.pagos set estado='"+ "DENEGADO, DEVOLUCIÓN"+"' where id='"+idPago+"'";
                    cmd4.ExecuteNonQuery();
                    conn.Close();
                    resp.Token = token;
                }
                catch (MySqlException e)
                {
                    InlineResponse400 resp2 = new InlineResponse400();
                    resp2.TypeError = "ERROR_PARAMETERS";
                    resp2.MessageError = "Los parámetros introducidos son erroneos.";
                    conn.Close();
                    Console.WriteLine(e.ToString());
                    return StatusCode(400, resp2);
                }
            }
            else
            {
                InlineResponse401 resp3 = new InlineResponse401();
                resp3.ErrorMessage = "ERROR_TOKEN";
                conn.Close();
                return StatusCode(401, resp3);
            }

            return StatusCode(201, resp);
        }
    }
}
